name: BkMito
version: ${project.version}
main: me.bkrmt.bkmito.BkMito
depend:
  - 'Vault'
softdepend:
  - 'Citizens'
  - 'HeroChat'
  - 'HeroChatPro'
  - 'Legendchat'
  - 'HolographicDisplays'
  - 'nChat'
  - 'PlaceholderAPI'
  - 'CombatLogX'
  - 'Factions'
  - 'PvPManager'
  - 'CombatTagPlus'
  - 'MyPet'
  - 'BkTeleport'
  - 'BkShop'
  - 'SimpleClans'
api-version: 1.13
authors: [ Bkr__ ]
description: Duel Plugin
